name: Build & Deploy Node.js App (server/) → Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install deps in server/
        working-directory: server
        run: npm install

      - name: (Optional) Build & Test in server/
        working-directory: server
        run: |
          npm run build --if-present
          npm run test  --if-present

      - name: Zip server/ contents
        run: |
          # Go into server/, zip its CONTENTS (not the folder itself)
          cd server
          zip -r ../artifact.zip ./*

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip into deploy_package/
        run: unzip artifact.zip -d deploy_package

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.AZUREAPPSERVICE_CLIENTID_320F8E2591CB4C89B3BAD31B7D3CCD56 }}
          tenant-id:     ${{ secrets.AZUREAPPSERVICE_TENANTID_9C85620426BC45EE8B067A7DA380CF59 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3BFC54E6592A458E8614C844D54DCEB7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name:    anon-share-server
          slot-name:   Production
          package:     ./deploy_package
