name: Deploy Node.js Server to Azure Web App - anon-share-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Zip server for deployment
        run: |
          cd server
          zip -r ../server-release.zip .

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_320F8E2591CB4C89B3BAD31B7D3CCD56 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9C85620426BC45EE8B067A7DA380CF59 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3BFC54E6592A458E8614C844D54DCEB7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'anon-share-server'
          slot-name: 'Production'
          package: server-release.zip
